-- MySQL Script generated by MySQL Workbench
-- jue 18 jul 2019 00:53:31 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iVoto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iVoto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iVoto` DEFAULT CHARACTER SET utf8 ;
USE `iVoto` ;

-- -----------------------------------------------------
-- Table `iVoto`.`estadoVotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`estadoVotacion` (
  `idestadoVotacion` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestadoVotacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`votacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`votacion` (
  `idvotacion` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NOT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  `fechaHoraInicio` DATETIME NOT NULL,
  `fechaHoraFin` DATETIME NOT NULL,
  `idestadoVotacion` INT(11) NOT NULL,
  PRIMARY KEY (`idvotacion`),
  INDEX `fk_votacion_estadoVotacion1_idx` (`idestadoVotacion` ASC),
  CONSTRAINT `fk_votacion_estadoVotacion1`
    FOREIGN KEY (`idestadoVotacion`)
    REFERENCES `iVoto`.`estadoVotacion` (`idestadoVotacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`candidato` (
  `idcandidato` INT(11) NOT NULL AUTO_INCREMENT,
  `puesto_candidato` VARCHAR(100) NOT NULL,
  `partido_politico` VARCHAR(100) NOT NULL,
  `idvotacion` INT(11) NOT NULL,
  `cantidadVotos` INT(11) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcandidato`),
  INDEX `fk_candidato_votacion1_idx` (`idvotacion` ASC),
  CONSTRAINT `fk_candidato_votacion1`
    FOREIGN KEY (`idvotacion`)
    REFERENCES `iVoto`.`votacion` (`idvotacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`estado_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`estado_usuario` (
  `idestado` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`persona` (
  `idpersona` INT(11) NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(10) NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `apellido_m` VARCHAR(45) NOT NULL,
  `huella_dactilar` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`tipo_usuario` (
  `idtipo` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARBINARY(100) NOT NULL,
  `contrasena` VARBINARY(100) NOT NULL,
  `persona_idpersona` INT(11) NOT NULL,
  `tipo_usuario_id` INT(11) NOT NULL,
  `estado_usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_persona_idx` (`persona_idpersona` ASC),
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_id` ASC),
  INDEX `fk_usuario_estado_usuario1_idx` (`estado_usuario_id` ASC),
  CONSTRAINT `fk_usuario_estado_usuario1`
    FOREIGN KEY (`estado_usuario_id`)
    REFERENCES `iVoto`.`estado_usuario` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `iVoto`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `iVoto`.`tipo_usuario` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `iVoto`.`votoDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iVoto`.`votoDetalle` (
  `idvotoDetalle` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaHoraVoto` DATETIME NOT NULL,
  `idvotacion` INT(11) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idvotoDetalle`),
  INDEX `fk_votoDetalle_votacion1_idx` (`idvotacion` ASC),
  INDEX `fk_votoDetalle_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_votoDetalle_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `iVoto`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votoDetalle_votacion1`
    FOREIGN KEY (`idvotacion`)
    REFERENCES `iVoto`.`votacion` (`idvotacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
